# Generated by Django 5.1.6 on 2025-03-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, verbose_name='MSU Denver Email')),
                ('Major', models.CharField(blank=True, choices=[('CSM-BS', 'Computer Science Major, B.S.'), ('DSML-BS', 'Data Science and machine Learning Major, B.S.'), ('CSciM', 'Computer Science Minor'), ('CSecM', 'Computer Security Minor')], max_length=200)),
            ],
        ),
    ]
