# Generated by Django 5.1.6 on 2025-03-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Major',
            field=models.CharField(choices=[('CSM-BS', 'Computer Science Major, B.S.'), ('DSML-BS', 'Data Science and machine Learning Major, B.S.'), ('CSciM', 'Computer Science Minor'), ('CSecM', 'Computer Security Minor')], max_length=200),
        ),
    ]
