# Generated by Django 5.1.6 on 2025-03-20 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_student_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.project'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
