# Generated by Django 5.1.6 on 2025-03-20 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_remove_project_portfolio_portfolio_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio_app.portfolio'),
        ),
        migrations.AlterField(
            model_name='student',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio'),
        ),
    ]
