# Generated by Django 5.1.6 on 2025-04-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_portfolio_portfolio_image_student_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
